# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.chamadointerno:
        container_name: laravel-chamadointerno-container
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        container_name: mysql-container
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
            - './database/data/chamados.sql:/docker-entrypoint-initdb.d/chamados.sql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    phpmyadmin:
        container_name: phpmyadmin-container
        image: phpmyadmin/phpmyadmin:latest
        environment:
          PMA_HOST: mysql
          PMA_USER: '${DB_USERNAME}'
          PMA_PASSWORD: '${DB_PASSWORD}'
          UPLOAD_LIMIT: 300M
        ports:
          - ${PMA_PORT:-8080}:80
        networks:
            - sail
    mailhog:
        container_name: mailhog-container
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
#    soketi:
#        image: 'quay.io/soketi/soketi:latest-16-alpine'
#        environment:
#            SOKETI_DEBUG: '1'
#            SOKETI_METRICS_SERVER_PORT: '9601'
#        ports:
#            - '${SOKETI_PORT:-6001}:6001'
#            - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
#        networks:
#            - nwchi
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
