# For more information: https://laravel.com/docs/sail
version: '3.0'
services:
    webserver:
        image: nginx:1.21.6-alpine
        container_name: webserver
        restart: unless-stopped
        ports:
        - '${APP_PORT:-80}:80'
        volumes:
        - ./:/var/www
        - ./.docker/nginx:/etc/nginx/conf.d
        networks:
            - app-network
    chamadosbackend:
        build:
            context: ./.docker/php
            dockerfile: Dockerfile
        container_name: chamadosbackend
        volumes:
            - '.:/var/www/'
            - './.docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini'
        networks:
            - app-network
        depends_on:
            - mysqlchamados
    mysqlchamados:
        image: 'mysql/mysql-server:8.0'
        container_name: mysqlchamados
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'chamados-mysql:/var/lib/mysql'
#            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        ports:
            - '$DB_PORT:3306'
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
    app-network:
        driver: bridge
volumes:
    chamados-mysql:
        driver: local
